#:schema node_modules/wrangler/config-schema.json
name = "xmas-list-worker"
main = "src/worker.ts"
account_id = "fd27ce0a0cea8a365d723f2a9a8b9184"
compatibility_date = "2024-09-02"

[[durable_objects.bindings]]
name = "SOCKET_OBJECT"
class_name = "SocketObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SocketObject"]
