#:schema node_modules/wrangler/config-schema.json
name = "xmas-list-worker"
main = "src/worker.ts"
compatibility_date = "2024-09-02"

[[durable_objects.bindings]]
name = "SOCKET_OBJECT"
class_name = "SocketObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SocketObject"]
