name: Deploy Sidecar Worker

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - 'common/**'
      - '.github/workflows/deploy-worker.yml'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: worker
        run: pnpm install --frozen-lockfile

      - name: Deploy
        working-directory: worker
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
